version: '3'
services:
  app-pgstac:
    container_name: stac-fastapi-pgstac
    image: alexgleith/stac-fastapi
    platform: linux/amd64
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST_READER=database
      - POSTGRES_HOST_WRITER=database
      - POSTGRES_PORT=5432
      - WEB_CONCURRENCY=10
      - VSI_CACHE=TRUE
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - DB_MIN_CONN_SIZE=1
      - DB_MAX_CONN_SIZE=1
      - USE_API_HYDRATE=${USE_API_HYDRATE:-false}
      - VIRTUAL_HOST=stac.dev.aodn.org.au
      - LETSENCRYPT_HOST=stac.dev.aodn.org.au
      - LETSENCRYPT_EMAIL=admin@aodn.org.au
    expose:
      - "80"
    volumes:
      - ./:/code
    depends_on:
      - database
    command:
      uvicorn stac_fastapi.pgstac.app:app --host 0.0.0.0 --port 80 --forwarded-allow-ips='*'
#        pip3 install gunicorn && gunicorn -k uvicorn.workers.UvicornWorker stac_fastapi.pgstac.app:app --port 5000

  database:
    container_name: stac-db
    image: postgis/postgis:14-3.2-alpine
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
      - PGUSER=username
      - PGPASSWORD=password
      - PGHOST=localhost
      - PGDATABASE=postgis
    ports:
      - "5432:5432"

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=mail@yourdomain.tld
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
